version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: deployment/docker/Dockerfile.dev
    container_name: mcp-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: mcp-redis
    ports:
      - "6379:6379"
    restart: always

  db:
    image: mysql:8.0
    container_name: mcp-mysql
    ports:
      - "3306:3306"
    environment:
      # These lines now read directly from your .env file
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data: